name: test_create_vvmp_by_ai_2
description: Flutter project with vvmp architecture
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vvmp: 
    path: E:/Libraries/My/Dart/Flutter/vvmp/
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
